version: '2'
services:
  mysql:
    image: mysql
    container_name: pchwo2018_83739
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=pdudka
      - MYSQL_PASSWORD=haslo
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
    - "3306:3306"
    networks:
      Bridge-Zadanie-1:
        ipv4_address: 10.0.10.3
  java:
    image: patrycjade/docker
    networks:
     Bridge-Zadanie-1:
    depends_on:
     - mysql
    links:
     - mysql
    ports:
    - "8080:3306"
networks:
  Bridge-Zadanie-1:
    driver: bridge
    ipam:
      config:
         - subnet: 10.0.10.0/24
           gateway: 10.0.10.1 
      
